language: node_js
node_js:
    - '8'
    - '9'
    - '10'
    - '11'
    - '12'
script:
    - 'npm test'
after_success:
    - 'npm run upload-coverage'
notifications:
    webhooks:
        urls:
            - 'https://www.travisbuddy.com/'
        on_success: never
        on_failure: always
        on_start: never
        on_cancel: never
        on_error: never
